### ISSUE TITLE
Plutus scripts are not stable under exports of Haskell file

### ISSUE THREAD

**Issue by Titan-C** [input-output-hk/Alonzo-testnet#54]
Maybe this belongs to the plutus repo, yet I want to ask this question.

With the newest stand of things. Using this repo on tag "purple-2", on a nix-shell of the corresponding plutus repo on commit 8c83c4abe211b4bbcaca3cdf1b2c0e38d0eb683f. I compile the the "plutus-helloworld" script, I get the exact same script file as is on the resources/plutus-scripts/HelloWorldInt.plutus. No surprises here, but keep the reference.

```bash
cabal run plutus-helloworld && sha256sum result.plutus
Writing output to: result.plutus
"Log output"
[]
"Ex Budget"
ExBudget {exBudgetCPU = ExCPU 1191020, exBudgetMemory = ExMemory 4100}
4ccaa8c855dab22626b164f9ba7f6392b55618353d93c0578c12278636938054  result.plutus
```
A minimal change on HelloWorld.hs
```diff
@@ -10,6 +10,7 @@
 module Cardano.PlutusExample.HelloWorld
   ( helloWorldSerialised
   , helloWorldSBS
+  , helloWorld
   ) where
```
Notice it is only, exporting the valuidator script from the module. I have not change it. And only the serialized script is actually used later by the executable that writes it to file. This alone produces noticeable change under compilation.
```bash
cabal run plutus-helloworld && sha256sum result.plutus
Up to date
Writing output to: result.plutus
"Log output"
[]
"Ex Budget"
ExBudget {exBudgetCPU = ExCPU 1101701, exBudgetMemory = ExMemory 3800}
1aea5fec8b597c7bcb59e471b550bf10b309e7c57c110da6ecfd08da729b6ad3  result.plutus
```
Notice how now the execution budget is lower on both CPU and Memory. On top of that the file size itself has dropped from 271 bytes to 243.

What is going on here?
How can we trust contracts if this non-related change to the script or it dependencies completely alter it. Here I'm exporting from the Module.

**Comment by kevinhammond** [comment]
The change in the compiled script size shows that the compilation of the script is different. The HelloWorld module is now exporting more endpoints, which could change how various definitions are compiled, and so affect the size of the compiled file.  You'd need to ask the Plutus team what impact that has, but Template Haskell can be tricky to unpick.  Generally, I'd expect that adding an export would actually increase rather than decrease sizes of compiled code.  So your changes are relevant to the script size and execution cost.

Note that the CPU steps and memory units reported here will be slightly less than the number required for full script execution, since there are additional costs associated with setting up context etc. when calling the script.

**Comment by michaelpj** [comment]
We don't promise stability under changes to the source files, I'm afraid. If you're very worried about that, you can always export the serialized script and use that until you're ready to do a new version.

**Comment by kevinhammond** [comment]
Thanks, Michael.  I will close this issue
