### ISSUE TITLE
Exercise 3 feedback/questions

### ISSUE THREAD

**Issue by DanTup** [input-output-hk/Alonzo-testnet#6]
I completed exercise 3 but some things weren't clear to me that I think could be made clearer:

- Why must the random number be passed as both `--tx-in-datum-value` and `--tx-in-redeemer-value`?
- How do execution units relate to the fee passed with `--fee`? Should they match? Should `--fee` be execution units + some additional fee for the transaction?
- Where are there two values in `--execution-units`?
- Why is the script called "always succeed" and described as always succeeding if the random number must be known to withdraw funds?
- Where is the source code for the script?

**Comment by DanTup** [comment]
> Why is the script called "always succeed" and described as always succeeding if the random number must be known to withdraw funds?

I had misunderstood that the validation of the Datum/hash was script-specific, but it turns out to be validated for all transactions. Perhaps this could be clearer in the docs ([here](https://plutus.readthedocs.io/en/latest/reference/glossary.html?highlight=datum#term-datum) or [here](https://plutus.readthedocs.io/en/latest/plutus/explanations/ledger.html?highlight=datum#scripts-and-the-extended-utxo-model))?

> Where is the source code for the script?

Knowing the above, I guess the source _is_ [this simple validator that always succeeds](https://github.com/input-output-hk/cardano-node/blob/f3f5fe1dde64e483c382a5eccce591fee6627ad5/plutus-example/plutus-example/src/Cardano/PlutusExample/Untyped/AlwaysSucceeds.hs).

**Comment by CarlosLopezDeLara** [comment]
> Why must the random number be passed as both --tx-in-datum-value and --tx-in-redeemer-value?
In this particular script the redeemer is not relevant, however the cli is enforcing the use of both to build the transaction. You could use any value on the redeemer and it would still succeed. Using the same as in datum is an arbitrary decision.

>  How do execution units relate to the fee passed with --fee? Should they match? Should --fee be execution units + some additional fee for the transaction?

This is correct for now --fee be execution units + some additional fee for the transaction? Soon this calculations will be done automatically. 

> Why is the script called "always succeed" and described as always succeeding if the random number must be known to withdraw funds?

Because that is the datum is the only validation performed. No other logic involved. For this exercise the datum was relevant so that each pioneer could try to redeem, if it didn't involve datum, everyone would be able to redeem other's participants ada easily, potentially leaving them without the ability to test the redeeming transaction.

> Where is the source code for the script?

It is a slightly modified  version of: https://github.com/input-output-hk/plutus/blob/ffa40bb7c91a575272f3b20b4628432396789360/plutus-ledger-api/src/Plutus/V1/Ledger/Examples.hs#L22

On exercise 4 we will provide source code of the script, and you will have to compile it

**Comment by DanTup** [comment]
@CarlosLopezDeLara thank you for the answers! It may be useful to add some of that info to the Exercise 3 docs for future readers too.

**Comment by kevinhammond** [comment]
Hi Dan - this should really be in the tutorial material rather than the exercise itself - we will make sure it is covered there

**Comment by DanTup** [comment]
@kevinhammond is that material published already? I've struggled to find much in the way of Plutus docs - a lot of the results in search engines searching for this are now 404s (I raised this at https://github.com/input-output-hk/cardano-documentation/issues/25).

**Comment by james-iohk** [comment]
@DanTup For the time being Plutus docs can be found at https://plutus.readthedocs.io/en/latest/index.html
