### ISSUE TITLE
Show working code for emulator trace and playground usage

### ISSUE THREAD

**Issue by tdiesler** [input-output-hk/Alonzo-testnet#66]
I tried to port some trivial emulator trace usage like [Free.hs](https://github.com/input-output-hk/plutus-pioneer-program/blob/main/code/week05/src/Week05/Free.hs) from the plutus-pioneer-program to this project, which currently fails (for me) with a plutus compile error related to plutus-contract.

Currently, I can neither get the emulator nor the playground working and there isn't sufficient debug logging during script validation either. Recent versions of the pioneer program don't seem to align with the 1.29.0 testnet, so I can't reliably copy from there.

Could we please have some document usage and examples for the emulator and perhaps even the playground in this project? Perhaps start simple with Free.hs - I guess that would already unblock further progress for me.

Ideally, this would find its way into [plutus-example](https://github.com/input-output-hk/cardano-node/tree/master/plutus-example/plutus-example/src/Cardano/PlutusExample) as well.

Depends: PR #65
Related to: https://github.com/input-output-hk/plutus/issues/3910

**Comment by kevinhammond** [comment]
This repository is specific to the on-chain code (that runs on the Cardano node).  I wouldn't expect the Plutus Playground to work yet with the on-chain code (only with the emulator) since the Plutus Application Backend (PAB) is not yet integrated with the node.  Once the PAB is integrated, you should be able to do what you want.

There is a new version of the node that has some improved debugging information.  This is not yet officially released.  

Meanwhile, we might be able to look at Free.hs for you.

**Comment by james-iohk** [comment]
Agree. We will definitely add PAB exercises when that's available because it is all about constructing and submitting actual transactions, unlike the emulator, which is best left for the Pioneers course.

Other than the emulator code, Free.hs is a simple policy so nothing to see here.

@tdiesler feel free to reopen this if there is any point we've missed.

**Comment by tdiesler** [comment]
Perhaps I don't (yet) fully understand the intended programming model for on-chain code. 

Here is what I would like to see not only in this system, but quite generally ...

* The ability to automatically/comprehensively test the exact code that is going to get deployed
* Comprehensive multilevel logging not only for the error case, but also for successful execution
* Final error feedback that can comprehensively tell what went wrong
* All logging should support parameterized messages

Especially the first point is critical. If I can't (automatically) test what gets deployed, there are no guarantees that the system will behave as intended. The other three points may be variations of each other.

I thought that this project is the stepping stone for what will eventually feed into comprehensive plutus examples. If so, it might be the right place to showcase how the system is intended to get used (i.e. show it here first).

Perhaps there are already issues that address the above, are there?

PS: I can't reopen the issue

**Comment by james-iohk** [comment]
Testing onchain code can be performed in various ways at different points of development. We have the playground and emulator, capability to spin up a local testnet, and actual testnets. There's also be tooling for static-code analysis, particularly in the interest of security (checking for known exploits). I think this will be made easier with PAB handling contract instances too.
As for logging/error feedback, this is a hot topic and is being tracked internally.

**Comment by tdiesler** [comment]
As they say: show me the code

Automated testing of stuff that then gets deployed onchain - unmodified of course.
